image:
  repository: vamsidv2010/chatbot-simple
  tag: c7de7a8f2701397e934e5c5bd60038edc7ec01f9
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8501

ollama:
  host: http://host.docker.internal:11434
  model: lfm2.5-thinking:latest

phoenix:
  enabled: true
  image: arizephoenix/phoenix:latest
  project: chatbot

replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
